[package]
name = "raytracer"
version = "0.1.0"
authors = ["Alessandro Moura <a.moura@abdn.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
